# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-16.18.11" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.18.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.18.11.tgz";
        sha512 = "3oJbGBUWuS6ahSnEq1eN2XrCyf4YsWI8OyCvo7c64zQJNplk3mO84t53o8lfTk+2ji59g5ycfc6qQ3fdHliHuA==";
      };
    };
    "@types/node-9.6.61" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "9.6.61";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-9.6.61.tgz";
        sha512 = "/aKAdg5c8n468cYLy2eQrcR5k6chlbNwZNGUj3TboyPa2hcO2QAJcfymlqPzMiRj8B6nYKXjzQz36minFE0RwQ==";
      };
    };
    "lean-client-js-core-3.3.1" = {
      name = "lean-client-js-core";
      packageName = "lean-client-js-core";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lean-client-js-core/-/lean-client-js-core-3.3.1.tgz";
        sha512 = "Br1BHuLgPISE7EnC8Mn5uKZC2LLPoWyC4d6vhB7eXhgBWX+EUU6YaYD7zBWscXTEP2i2EwsFbiYuJtd/8/pnpw==";
      };
    };
    "lean-client-js-node-3.3.1" = {
      name = "lean-client-js-node";
      packageName = "lean-client-js-node";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lean-client-js-node/-/lean-client-js-node-3.3.1.tgz";
        sha512 = "AAZN7Kvwp2+UDGZPjSC3WEkursgPB/4WNrgFlG+9CaOcaIhWXg1XYax/JmIDTkZVRCi1YgKi785AAU2QIqHCOQ==";
      };
    };
    "vscode-jsonrpc-6.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-6.0.0.tgz";
        sha512 = "wnJA4BnEjOSyFMvjZdpiOwhSq9uDoK8e/kpRJDTaMYzwlkrhG1fwDIZI94CLsLzlCK5cIbMMtFlJlfR57Lavmg==";
      };
    };
    "vscode-languageserver-7.0.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-7.0.0.tgz";
        sha512 = "60HTx5ID+fLRcgdHfmz0LDZAXYEV68fzwG0JWwEPBode9NuMYTIxuYXPg4ngO8i8+Ou0lM7y6GzaYWbiDL0drw==";
      };
    };
    "vscode-languageserver-protocol-3.16.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.16.0.tgz";
        sha512 = "sdeUoAawceQdgIfTI+sdcwkiK2KU+2cbEYA0agzM2uqaUy2UpnnGHtWTHVEtS0ES4zHU0eMFRGN+oQgDxlD66A==";
      };
    };
    "vscode-languageserver-textdocument-1.0.8" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.8.tgz";
        sha512 = "1bonkGqQs5/fxGT5UchTgjGVnfysL0O8v1AYMBjqTbWQTFn721zaPGDYFkOKtfDgFiSgXM3KwaG3FMGfW4Ed9Q==";
      };
    };
    "vscode-languageserver-types-3.16.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.16.0.tgz";
        sha512 = "k8luDIWJWyenLc5ToFQQMaSrqCHiLwyKPHKPQZ5zz21vM+vIVUSvsRpcbiECH4WR88K2XZqc4ScRcZ7nk/jbeA==";
      };
    };
    "vscode-uri-3.0.7" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.7.tgz";
        sha512 = "eOpPHogvorZRobNqJGhapa0JdwaxpjVvyBp0QIUMRMSf8ZAlqOdEquKuRmw9Qwu0qXtJIWqFtMkmvJjUZmMjVA==";
      };
    };
  };
in
{
  lean-language-server = nodeEnv.buildNodePackage {
    name = "lean-language-server";
    packageName = "lean-language-server";
    version = "3.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/lean-language-server/-/lean-language-server-3.4.0.tgz";
      sha512 = "Qb4+jCU2V06LfQVApyyzXlzG8H0KlKUO9HqJmWq8BMxSvfXpnGxGRyKRoQEcBHNJl6Y2+UXQCo0/mEVy13DwnA==";
    };
    dependencies = [
      sources."@types/node-16.18.11"
      (sources."lean-client-js-core-3.3.1" // {
        dependencies = [
          sources."@types/node-9.6.61"
        ];
      })
      (sources."lean-client-js-node-3.3.1" // {
        dependencies = [
          sources."@types/node-9.6.61"
        ];
      })
      sources."vscode-jsonrpc-6.0.0"
      sources."vscode-languageserver-7.0.0"
      sources."vscode-languageserver-protocol-3.16.0"
      sources."vscode-languageserver-textdocument-1.0.8"
      sources."vscode-languageserver-types-3.16.0"
      sources."vscode-uri-3.0.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Language Server Protocol server for Lean 3";
      homepage = "https://github.com/leanprover/lean-client-js#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
